board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.board_list, name='list'),
    path('<int:board_id>/', views.board_view, name='view'),
    path('add', views.board_add, name='add'),
]

coininfo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('reETH',views.ETH_refresh),
    path('reBTC',views.BTC_refresh),
    path('reXRP',views.XRP_refresh),
    path('XRP',views.XRP_view),
    path('BTC',views.BTC_view),
    path('ETH',views.ETH_view),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

def home_view(request):
    return render(request, 'home.html')

def chart_view(request):
    return  render(request, 'chartpage.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('board/', include('board.urls')),
    path('user/', include('users_app.urls')),
    path('info/', include('coininfo.urls')),
    path('chartpage/', chart_view)
]

users_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users_app'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users_app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

board/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class CoinBoard(models.Model):
    write_time = models.DateTimeField(auto_now_add=True)
    board_title = models.CharField(max_length=100)
    write_user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()

    def __str__(self):
        return f"게시글 제목은 {self.board_title}이고, 내용은 {self.content}"

coininfo/models.py
from django.db import models

# Create your models here.
class CoinInfoETH(models.Model):    #이더리움
    cd = models.CharField(max_length=10)
    tp = models.IntegerField()
    scr = models.FloatField()
    tv = models.FloatField()

class CoinInfoBTC(models.Model):    #비트코인
    cd = models.CharField(max_length=10)
    tp = models.IntegerField()
    scr = models.FloatField()
    tv = models.FloatField()

class CoinInfoXRP(models.Model):    #리플
    cd = models.CharField(max_length=10)
    tp = models.IntegerField()
    scr = models.FloatField()
    tv = models.FloatField()

class CoinInfoDKA(models.Model):    #디카르고
    cd = models.CharField(max_length=10)
    tp = models.IntegerField()
    scr = models.FloatField()
    tv = models.FloatField()

class CoinInfoDOGE(models.Model):    #도지코인
    cd = models.CharField(max_length=10)
    tp = models.IntegerField()
    scr = models.FloatField()
    tv = models.FloatField()

users_app/models.py
from django.db import models

# Create your models here.

board/forms.py
from django import forms
from .models import CoinBoard

class BoardAdd(forms.ModelForm):
    class Meta:
        model = CoinBoard
        fields = ('board_title', 'content')
        exclude = ('write_user',)
        labels = {
            'board_title':'제목을 입력하세요.',
            'content':'내용을 입력하세요.',
        }

users_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "email"]

board/views.py
from django.shortcuts import render, redirect
from .models import CoinBoard
from .forms import BoardAdd
from django.urls import reverse
# Create your views here.

def board_list(request):
    boardlist = CoinBoard.objects.order_by('-write_time')
    context = {'boardlist':boardlist}
    return render(request,'board/board_list.html',context=context)

def board_view(request, board_id):
    board_detail = CoinBoard.objects.get(id=board_id)
    context = {'board_detail':board_detail}
    return render(request,'board/board_view.html',context=context)

def board_add(request):
    if request.method == 'POST':
        boardform = BoardAdd(request.POST)
        if boardform.is_valid():
            print(boardform.cleaned_data)#디버그용
            post = boardform.save(commit=False)
            post.write_user = request.user
            post.save()
            return redirect(reverse('board:list'))
    else:
        boardform = BoardAdd()
    return render(request,'board/board_add.html',context={'boardform':boardform})

coininfo/views.py
from django.shortcuts import render
from coininfo.models import CoinInfoETH, CoinInfoBTC, CoinInfoXRP
import csv

def ETH_refresh(request):
    path = 'C:\projects\mysite\static\ETH.csv'
    file = open(path)
    ETH_reader = csv.reader(file)
    list = []
    for row in ETH_reader:
        if row[0] != 'cd':
            list.append(CoinInfoETH(cd=row[0],
                                    tp=row[1],
                                    scr=row[2],
                                    tv=row[3]))
    CoinInfoETH.objects.bulk_create(list)
    ETH_data = CoinInfoETH.objects.all()
    return render(request,'home.html',context={'ETH_data':ETH_data})

def BTC_refresh(request):
    path = 'C:\projects\mysite\static\BTC.csv'
    file = open(path)
    BTC_reader = csv.reader(file)
    list = []
    for row in BTC_reader:
        if row[0] != 'cd':
            list.append(CoinInfoBTC(cd=row[0],
                                    tp=row[1],
                                    scr=row[2],
                                    tv=row[3]))
    CoinInfoBTC.objects.bulk_create(list)
    BTC_data = CoinInfoBTC.objects.all()
    return render(request,'home.html',context={'BTC_data':BTC_data})

def XRP_refresh(request):
    path = 'C:\projects\mysite\static\XRP.csv'
    file = open(path)
    XRP_reader = csv.reader(file)
    list = []
    for row in XRP_reader:
        if row[0] != 'cd':
            list.append(CoinInfoXRP(cd=row[0],
                                    tp=row[1],
                                    scr=row[2],
                                    tv=row[3]))
    CoinInfoXRP.objects.bulk_create(list)
    XRP_data = CoinInfoXRP.objects.all()
    return render(request,'home.html',context={'XRP_data':XRP_data})

def ETH_view(request):
    return render(request,'chartpage.html')

def BTC_view(request):
    return render(request,'chartpage.html')

def XRP_view(request):
    return render(request,'chartpage.html')

users_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import UserForm
from django.contrib.auth import authenticate, login

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(reverse('home'))
    else:
        form = UserForm()
    return render(request, 'users_app/signup.html', {'form': form})

board/templates/board/board_add.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시글등록</h5>
    <form method="POST">
        {% csrf_token %}
        {% if boardform.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in boardform %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <div class="mb-3">
            <label for="board_title" class="form-label">제목을 입력하세요</label>
            <input type="text" class="form-control" name="board_title" id="board_title"
                   value="{{ boardform.board_title.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용을 입력하세요</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ boardform.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">등록</button>
    </form>
</div>
{% endblock %}

board/templates/board/board_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>작성일시</th>
            <th>제목</th>
            <th>작성자</th>
        </tr>
        </thead>
        <tbody>
        {% if boardlist %}
        {% for item in boardlist %}
        <tr>
            <td>{{item.write_time}}</td>
            <td><a href="{% url 'board:view' board_id=item.id %}">{{item.board_title}}</a></td>
            <td>{{item.write_user}}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">게시글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'board:add' %}" class="btn btn-primary">글쓰기</a>
</div>
{% endblock %}

board/templates/board/board_view.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{board_detail.board_title}}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{board_detail.content}}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{board_detail.write_time}}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>캡스톤디자인</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/chartpage.html
<!doctype html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>chartpage</title>

    <link rel="stylesheet" href="fontawesome\css\all.css" >

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        
</head>

<body>
    {% include "navbar.html" %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>

</html>

<head>
    <style>
        h1 {
            margin-top: 500px;
            display: block;
            margin: 0 auto;
            font-family: 'Jura';
            font-style: normal;
            font-weight: 500;
            font-size: 40px;
            line-height: 50px;
            margin-top: 283px;
            text-align: center;
            color: #000000;
            height: 100px;

        }

        #chartbox {
            width: 407px;
            height: 269px;
            background-color: #aeabab;
            border: 0px solid rgb(0, 0, 0);
            border-radius: 3%;
        }

        .row {

            text-align: center;
            /* display: block; */
            font-size: 16px;
            border-bottom: 1px solid #eee;
            padding: 11px 0;

        }

        #trading_volum {
            width: 100%;
            height: 92%;
            background-color: #aeabab;
            border: 0px solid rgb(0, 0, 0);
            border-radius: 3%;
        }

        li,
        ol,
        ul {
            list-style: none;
        }

        #chart_box {

            height: 400px;
        }

        #notice_board {
            width: 100%;
            height: 258px;
            background-color: #aeabab;
            border: 0px solid rgb(0, 0, 0);
            border-radius: 3%;
        }

        #left_layout {
            width: 60%;
        }

        #right_layout {
            width: 40%;
        }

        #navbar {
            width: 100%;
            height: 100;
            margin-bottom: 100px;
        }
        #left_box{
            display: block;
        }
    </style>

</head>

<body>
    <!-- 메인 박스 -->
    <div class="container text-center">
        <div class="row">
            <div class="col" id="navbar"></div>
            <!-- 네브 빠 -->
        </div>
        <div class="row">
            <div class="col-8" id="left_layout">

                <div class="row" id="left_box">

                    <div class="col" id="chart_box">
                        
                        <!-- 주식차트 넣을곳 -->
                    </div>
                    <div class="col" id="notice_board">
                        <!-- 게시판 넣을곳 -->
                        <p>실시간 반응</p>
                    </div>
                </div>
            </div>

            <div class="col-4" id="right_layout">
                <!-- 실시간 거래량 많은 차트 -->
                <p> 실시간 하락 종목</p>
                <table id="trading_volum">
                    <tbody>
                        <tr>
                            <td>종목명</td>
                            <td>현재가</td>
                            <td>전일대비</td>
                            <td>동락률</td>
                        </tr>
                        <tr>
                            <td>종목명2</td>
                            <td>현재가</td>
                            <td>전일대비</td>
                            <td>동락률</td>
                        </tr>
                        <tr>
                            <td>종목명3</td>
                            <td>현재가</td>
                            <td>전일대비</td>
                            <td>동락률</td>
                        </tr>
                        <tr>
                            <td>종목명4</td>
                            <td>현재가</td>
                            <td>전일대비</td>
                            <td>동락률</td>
                        </tr>
                        <tr>
                            <td>종목명5</td>
                            <td>현재가</td>
                            <td>전일대비</td>
                            <td>동락률</td>
                        </tr>
                        <tr>
                            <td>종목명5</td>
                            <td>현재가</td>
                            <td>전일대비</td>
                            <td>동락률</td>
                        </tr>
                        <tr>
                            <td>종목명5</td>
                            <td>현재가</td>
                            <td>전일대비</td>
                            <td>동락률</td>
                        </tr>
                        <tr>
                            <td>종목명5</td>
                            <td>현재가</td>
                            <td>전일대비</td>
                            <td>동락률</td>
                        </tr>

                    </tbody>
                </table>
            </div>

        </div>
    </div>
</body>

</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/home.html
<!doctype html>
<html lang="ko">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>APImain</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    
</head>

<body>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
{% include "navbar.html" %}
</body>

</html>

<head>
  <style>
    h1 {
      margin-top: 100px;
      display: block;
      margin: 0 auto;
      font-family: 'Jura';
      font-style: normal;
      font-weight: 500;
      font-size: 40px;
      line-height: 50px;
      margin-top: 283px;
      text-align: center;
      color: #000000;
      height: 100px;

    }

    #chartbox {
      width: 407px;
      height: 269px;
      background-color: #aeabab;
      border: 0px solid rgb(0, 0, 0);
      border-radius: 3%;
    }

    .row {

      text-align: center;
      /* display: block; */
      font-size: 16px;
      border-bottom: 1px solid #eee;
      padding: 11px 0;

    }

    li,
    ol,
    ul {
      list-style: none;
    }

    .top_item, .bottom_item {
      /* border: 1px solid #000000; */
      width: 100%;
      height: 80%;
      margin-top: 5px;
      font-size: 13px;

    }


    #right_box,
    #left_box {
      width: 300px;
      height: 300px;
      border: 0px;
      background-color: #d3d3d3;
      margin: 5px;
      border-radius: 28px;
    }

    input {
      display: block;
      margin: 0 auto;
      width: 700px;
      height: 73px;
      border-radius: 60px;
    }
  </style>

</head>

<body>
  <!-- 메인 박스 -->

  <div id="container" role="main">
    <div class="container text-center">

      <div class="row">
        <div class="col">
          <h1></h1>
          <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="무엇이든 검색하세요" aria-label="무엇이든 검색하세요" aria-describedby="button-addon2">
            <button class="btn btn-outline-secondary" type="button" onclick="location.href='chartpage'"  id="button-addon2">
            <i class="fa-solid fa-magnifying-glass"></i>
            {% comment %} 검색창 수정 {% endcomment %}
            </button>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="col" id="left_box">
          <p> 실시간 상승 종목</p>

          <table class="top_item">
            <tbody>
              <tr>
                <td>{{ETH_data}}</td>
                <td>현재가</td>
                <td>전일대비</td>
                <td>동락률</td>
              </tr>
              <tr>
                <td>{{BTC_data}}</td>
                <td>현재가</td>
                <td>전일대비</td>
                <td>동락률</td>
              </tr>
              <tr>
                <td>{{XRP_data}}</td>
                <td>현재가</td>
                <td>전일대비</td>
                <td>동락률</td>
              </tr>
            </tbody>
          </table>

        </div>
        <div class="col" id="right_box">
          <p> 실시간 하락 종목</p>
          <table class="bottom_item">
            <tbody>
              <tr>
                <td>종목명</td>
                <td>현재가</td>
                <td>전일대비</td>
                <td>동락률</td>
              </tr>
              <tr>
                <td>종목명2</td>
                <td>현재가</td>
                <td>전일대비</td>
                <td>동락률</td>
              </tr>
              <tr>
                <td>종목명3</td>
                <td>현재가</td>
                <td>전일대비</td>
                <td>동락률</td>
              </tr>
            </tbody>
          </table>


        </div>
      </div>
    </div>
  </div>




</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'users_app:logout' %}">로그아웃</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'users_app:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'users_app:signup' %}">회원가입</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'board:list' %}">게시판</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

users_app/templates/users_app/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'users_app:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

users_app/templates/users_app/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'users_app:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 재확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">본인 확인 이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">가입하기</button>
    </form>
</div>
{% endblock %}